name: cropper_custom
description: A Flutter package for cropping
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: any
  image_picker: ^0.8.6
  helpers: ^1.2.0
  image: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  path: ^1.8.0
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
